name: test prune script

on:
  push:
    paths:
      - 'scripts/prune/**'
      - .github/workflows/test-prune-script.yml
    branches: [main]
  pull_request:
    paths:
      - 'scripts/prune/**'
      - .github/workflows/test-prune-script.yml
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: scripts/prune

    steps:
      - name: Check out repository
        uses: actions/checkout@main

      - name: Set up Python 3.13
        uses: actions/setup-python@main
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@main
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/prune/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          echo "Running unit tests"
          python tests/test_prune.py

      - name: Run integration tests
        run: |
          echo "Running integration tests"
          python tests/test_integration.py

      - name: Run all tests via test runner
        run: |
          echo "Running comprehensive test suite"
          echo "Using Python: $(which python)"
          python test_runner.py

      - name: Check script can show help
        run: |
          echo "Testing CLI help interface"
          python main.py --help
